In [151]:
import pandas as pd


In [152]:
df=pd.read_csv("diabetes_risk.csv")

In [153]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low


In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   patient_id                15000 non-null  int64  
 1   age                       15000 non-null  int64  
 2   gender                    15000 non-null  object 
 3   city                      15000 non-null  object 
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  object 
 6   physical_activity_level   15000 non-null  object 
 7   diet_type                 15000 non-null  object 
 8   smoking_status            14528 non-null  object 
 9   alcohol_consumption       11212 non-null  object 
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64  
 12  fasting_blood_sugar       15000 non-null  int64  
 13  hba1c_level               15000 non-null  float64
 14  blood_

In [155]:
df.shape

(15000, 19)

In [156]:
df.isnull().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [157]:
#print top 10 rows of only null columns
df[df.columns[df.isnull().any()]].head(10)

,smoking_status,alcohol_consumption,income_bracket
0,Never,Never,High
1,Never,Never,Low
2,Current,Regular,Low
3,Never,Never,Middle
4,Current,Occasional,High
5,Never,Occasional,High
6,NaN,NaN,High
7,Never,Never,Middle
8,Current,Never,High
9,Current,Occasional,High


In [158]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [159]:
df.isnull().sum()

patient_id                  0
age                         0
gender                      0
city                        0
bmi                         0
family_history_diabetes     0
physical_activity_level     0
diet_type                   0
smoking_status              0
alcohol_consumption         0
hours_sleep_per_night       0
stress_level                0
fasting_blood_sugar         0
hba1c_level                 0
blood_pressure_systolic     0
blood_pressure_diastolic    0
waist_circumference_cm      0
income_bracket              0
diabetes_risk               0
dtype: int64

In [160]:
X=df.drop(['diabetes_risk','patient_id'], axis=1)
y=df['diabetes_risk']

In [161]:
y

0             Low
1             Low
2            High
3             Low
4             Low
           ...   
14995        High
14996         Low
14997         Low
14998         Low
14999    Moderate
Name: diabetes_risk, Length: 15000, dtype: object

In [162]:
#encode the categorical columns using one hot encoding
X = pd.get_dummies(X, columns=X.select_dtypes(include='object').columns)
#y with label encoding
y = y.map({'Low': 0, 'Moderate':1,'High': 2})

In [163]:
X

,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,gender_Female,...,diet_type_Vegetarian,smoking_status_Current,smoking_status_Former,smoking_status_Never,alcohol_consumption_Never,alcohol_consumption_Occasional,alcohol_consumption_Regular,income_bracket_High,income_bracket_Low,income_bracket_Middle
0,47,26.5,9.0,8,178,7.3,146,90,107.1,True,...,True,False,False,True,True,False,False,True,False,False
1,53,20.5,7.0,6,152,6.9,156,100,93.8,True,...,True,False,False,True,True,False,False,False,True,False
2,47,31.3,7.0,7,168,6.6,150,102,113.5,False,...,False,True,False,False,False,False,True,False,True,False
3,41,22.8,9.0,5,155,6.7,126,92,109.6,False,...,False,False,False,True,True,False,False,False,False,True
4,57,16.7,6.5,10,188,6.7,130,90,80.8,True,...,False,True,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,47,37.7,6.8,7,213,8.1,150,100,141.7,False,...,False,False,False,True,True,False,False,True,False,False
14996,48,20.6,6.0,8,162,6.5,132,80,91.0,True,...,False,False,False,True,True,False,False,False,False,True
14997,34,17.9,7.0,6,137,6.5,136,90,88.8,True,...,True,False,False,True,True,False,False,False,True,False
14998,56,20.7,6.0,5,163,6.9,140,87,94.8,False,...,True,False,False,True,True,False,False,False,True,False


In [164]:
y.unique()

array([0, 2, 1], dtype=int64)

In [165]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [166]:
print(X_train.shape)
print(X_test.shape)

print(X_train.mean())
print(X_train.std())

(12000, 48)
(3000, 48)
age                                   44.374333
bmi                                   23.078067
hours_sleep_per_night                  7.305067
stress_level                           5.954417
fasting_blood_sugar                  168.887250
hba1c_level                            6.881967
blood_pressure_systolic              139.556083
blood_pressure_diastolic              86.261667
waist_circumference_cm               100.251942
gender_Female                          0.481750
gender_Male                            0.508333
gender_Other                           0.009917
city_Ahmedabad                         0.069500
city_Bengaluru                         0.101000
city_Bhopal                            0.025083
city_Chennai                           0.063583
city_Delhi                             0.115833
city_Hyderabad                         0.082000
city_Indore                            0.029917
city_Jaipur                            0.041083
city_Kanpur      

In [167]:
#scale the data using standard scaler
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)


In [168]:
import torch
#convert to pytorch tensors
x_train_tensor = torch.tensor(x_train_scaled, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values.squeeze(), dtype=torch.long)
y_test_tensor= torch.tensor(y_test.values.squeeze(),dtype=torch.long)

.values = Pandas → NumPy
.squeeze() = remove unnecessary dimensions
torch.tensor() = NumPy → PyTorch
long = integer class labels for CrossEntropyLoss

In [169]:
print(x_train_tensor.shape)
print(x_test_tensor.shape)

print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([12000, 48])
torch.Size([3000, 48])
torch.Size([12000])
torch.Size([3000])


In [170]:
from torch.utils.data import Dataset,DataLoader
class customdataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self,idx):
        return self.features[idx],self.labels[idx]

In [171]:
train_dataset=customdataset(x_train_tensor,y_train_tensor)
test_dataset=customdataset(x_test_tensor,y_test_tensor)

In [172]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=False)

In [173]:
print(len(train_loader))
print(len(test_loader))

375
94


In [174]:
x_batch,y_batch=next(iter(train_loader))
print(x_batch.shape)
print(y_batch.shape)

torch.Size([32, 48])
torch.Size([32])


Important difference

next(iter(train_loader)) by itself does NOT automatically go through all batches.

It gets only the next one batch.

The for loop is what keeps asking for the next batch until the DataLoader is finished.

So remember:

iter() = prepare to go through batches
next() = get the next batch
for loop = keep getting batches until finished.

super().__init__()

says:

"Set up all the basic PyTorch model functionality for me."

In [178]:
import torch.nn as nn
class logisticnn(nn.Module):
    def __init__(self,input_dim):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(input_dim,64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Linear(64,32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Linear(32,3)
        )

    def forward(self,features):
        return self.network(features)
    
model=logisticnn(48)
print(model)
prediction=model(x_batch)
print(prediction.shape)

logisticnn(
  (network): Sequential(
    (0): Linear(in_features=48, out_features=64, bias=True)
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=64, out_features=32, bias=True)
    (4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=3, bias=True)
  )
)
torch.Size([32, 3])


In [179]:
loss_function=nn.CrossEntropyLoss()

In [180]:
print(prediction.shape)
print(y_batch.shape)
print(y_batch.dtype)

torch.Size([32, 3])
torch.Size([32])
torch.int64


In [181]:
print(y_batch.shape)
print(y_batch.dtype)

torch.Size([32])
torch.int64


In [182]:
x_batch, y_batch = next(iter(train_loader))

print("X:", x_batch.shape)
print("y:", y_batch.shape)
print("y dtype:", y_batch.dtype)
print("y:", y_batch[:10])

X: torch.Size([32, 48])
y: torch.Size([32])
y dtype: torch.int64
y: tensor([0, 0, 2, 2, 1, 2, 1, 1, 2, 1])


In [183]:
loss=loss_function(prediction,y_batch)
print(loss)

tensor(1.1101, grad_fn=<NllLossBackward0>)


In [184]:
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)


In **very simple words**:

### BatchNorm = keeps the numbers under control

Your neural network produces numbers like:

```text
1000, 0.2, -500, 30, 2000
```

These numbers can be very different in size.

**BatchNorm makes them more balanced and stable** before sending them to the next layer.

Think of it like:

```text
Linear
  ↓
Messy numbers 😵
  ↓
BatchNorm
  ↓
More balanced numbers 👍
  ↓
ReLU
```

So:

```python
nn.Linear(48, 64)
nn.BatchNorm1d(64)
nn.ReLU()
```

means:

**"Create 64 numbers → make them more stable → then apply ReLU."**

That's basically it.


In [185]:
epochs=50

for epoch in range(epochs):
    for x_batch,y_batch in train_loader:
        # forward pass
        prediction=model(x_batch)
        #calculate_loss
        loss=loss_function(prediction,y_batch)
        #clear old gradients
        optimizer.zero_grad()
        #backpropagation
        loss.backward()
        #update weights
        optimizer.step()
    if (epoch+1)%10==0:
        print(f"epoch[{epoch+1}/{epochs}],Loss:{loss.item():4f}")

epoch[10/50],Loss:0.439521
epoch[20/50],Loss:0.432276
epoch[30/50],Loss:0.393013
epoch[40/50],Loss:0.313848
epoch[50/50],Loss:0.502660


In [186]:
model.eval()

logisticnn(
  (network): Sequential(
    (0): Linear(in_features=48, out_features=64, bias=True)
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=64, out_features=32, bias=True)
    (4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=32, out_features=3, bias=True)
  )
)

In [187]:
model.eval()

correct = 0
total = 0

with torch.no_grad():

    for x_batch, y_batch in test_loader:

        prediction = model(x_batch)

        predicted_classes = torch.argmax(prediction, dim=1)

        total += y_batch.size(0)

        correct += (predicted_classes == y_batch).sum().item()

accuracy = correct / total

print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 75.57%


In [188]:
from sklearn.metrics import confusion_matrix

model.eval()

all_predictions = []
all_labels = []

with torch.no_grad():
    for x_batch, y_batch in test_loader:

        prediction = model(x_batch)

        predicted_classes = torch.argmax(prediction, dim=1)

        all_predictions.extend(predicted_classes.numpy())
        all_labels.extend(y_batch.numpy())

cm = confusion_matrix(all_labels, all_predictions)

print(cm)

[[1577  221   21]
 [ 266  381  102]
 [  20  103  309]]


In [189]:
from sklearn.metrics import classification_report

print(classification_report(all_labels, all_predictions))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1819
           1       0.54      0.51      0.52       749
           2       0.72      0.72      0.72       432

    accuracy                           0.76      3000
   macro avg       0.70      0.70      0.70      3000
weighted avg       0.75      0.76      0.75      3000



In [190]:
len(test_loader)

94

In [191]:
torch.save(model.state_dict(), "diabetesprediction.pth")

In [192]:
import joblib

joblib.dump(scaler, "diabetesscaler.pkl")

['diabetesscaler.pkl']

In [193]:
import torch
import joblib

model = logisticnn(48)

model.load_state_dict(
    torch.load("diabetesprediction.pth")
)

model.eval()

scaler = joblib.load("diabetesscaler.pkl")

In [194]:
X.columns

Index(['age', 'bmi', 'hours_sleep_per_night', 'stress_level',
       'fasting_blood_sugar', 'hba1c_level', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'waist_circumference_cm', 'gender_Female',
       'gender_Male', 'gender_Other', 'city_Ahmedabad', 'city_Bengaluru',
       'city_Bhopal', 'city_Chennai', 'city_Delhi', 'city_Hyderabad',
       'city_Indore', 'city_Jaipur', 'city_Kanpur', 'city_Kolkata',
       'city_Lucknow', 'city_Mumbai', 'city_Nagpur', 'city_Patna', 'city_Pune',
       'city_Surat', 'city_Thane', 'city_Visakhapatnam',
       'family_history_diabetes_No', 'family_history_diabetes_Yes',
       'physical_activity_level_Active', 'physical_activity_level_Moderate',
       'physical_activity_level_Sedentary', 'diet_type_Non-Vegetarian',
       'diet_type_Pescatarian', 'diet_type_Vegan', 'diet_type_Vegetarian',
       'smoking_status_Current', 'smoking_status_Former',
       'smoking_status_Never', 'alcohol_consumption_Never',
       'alcohol_consumption_O

In [195]:
new_data = pd.DataFrame({
    "age":[50],
    "bmi":[31.5],
    "hours_sleep_per_night":[7.0],
    "stress_level":[8],
    "fasting_blood_sugar":[180],
    "hba1c_level":[7.1],
    "blood_pressure_systolic":[145],
    "blood_pressure_diastolic":[95],
    "waist_circumference_cm":[105]
})

In [196]:
new_data = pd.get_dummies(new_data)

new_data = new_data.reindex(
    columns=X.columns,
    fill_value=0
)

In [197]:
new_data_scaled = scaler.transform(new_data)

In [198]:
new_tensor = torch.tensor(
    new_data_scaled,
    dtype=torch.float32
)

In [199]:
model.eval()

with torch.no_grad():
    logits = model(new_tensor)

predicted_class = torch.argmax(
    logits,
    dim=1
).item()

print(predicted_class)

2


In [200]:
label_map = {
    0: "Low",
    1: "Moderate",
    2: "High"
}

print(
    "Predicted Risk:",
    label_map[predicted_class]
)

Predicted Risk: High


In [201]:
with torch.no_grad():
    logits = model(new_tensor)

probabilities = torch.softmax(
    logits,
    dim=1
)

print(probabilities)

tensor([[0.0455, 0.4567, 0.4978]])


Absolutely. Here is the **summary of the errors you encountered**, why they happened, and how you fixed them. This is worth keeping as your PyTorch notes. 📝

# PyTorch Multiclass Classification — Error Summary

Your project was a **3-class classification problem**, where:

```text
0 = Class 0
1 = Class 1
2 = Class 2
```

Your model had:

```text
49 input features
      ↓
Linear(49 → 32)
      ↓
ReLU
      ↓
Linear(32 → 16)
      ↓
ReLU
      ↓
Linear(16 → 3)
```

---

## 1. ❌ Wrong layer size

Initially you wrote:

```python
nn.Linear(input_dim, 3),
nn.ReLU(),
nn.Linear(32, 16)
```

### Why was this wrong?

The first layer produced **3 outputs**:

```text
49 → 3
```

But the next layer expected **32 inputs**:

```text
32 → 16
```

So you were connecting:

```text
3 outputs → 32 inputs ❌
```

### Correct:

```python
nn.Linear(input_dim, 32)
nn.ReLU()
nn.Linear(32, 16)
nn.ReLU()
nn.Linear(16, 3)
```

Now:

```text
49 → 32 → 16 → 3
```

Every layer connects correctly.

---

# 2. ❌ Missing comma

You had:

```python
nn.ReLU()
nn.Linear(16,3)
```

Python needs a comma between the items inside `nn.Sequential`.

Correct:

```python
nn.ReLU(),
nn.Linear(16,3)
```

---

# 3. ❌ Scaling `y`

You initially did:

```python
y_train_scaled = scaler.fit_transform(
    y_train.values.reshape(-1,1)
)
```

This was wrong for classification.

### Why?

Your `y` contains class labels:

```text
0
1
2
```

These are **categories**, not continuous measurements.

You should scale your input features:

```python
X → StandardScaler ✅
```

but don't scale your class labels:

```python
y → 0, 1, 2 ❌ don't scale
```

### Correct:

```python
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)
```

Keep:

```python
y_train
y_test
```

unchanged.

---

# 4. ❌ Wrong `y` dtype

You initially had:

```text
y_batch dtype = torch.float32
```

But you're using:

```python
nn.CrossEntropyLoss()
```

For multiclass classification, `CrossEntropyLoss` expects class indices as integers.

So:

```text
float32 ❌
int64 / long ✅
```

Therefore:

```python
y_train_tensor = torch.tensor(
    y_train.values,
    dtype=torch.long
)
```

---

# 5. ❌ Wrong `y` shape

This was your main error:

```text
prediction → [32, 3] ✅

y_batch → [32, 1] ❌
```

The error was:

```text
0D or 1D target tensor expected,
multi-target not supported
```

### Why?

You have 32 samples in the batch.

You need **one class number for each sample**:

```text
[0, 1, 2, 0, 1, 2, ...]
```

Therefore:

```text
[32] ✅
```

But you had:

```text
[[0],
 [1],
 [2],
 ...]
```

which is:

```text
[32, 1] ❌
```

---

# 6. ✅ Why `.squeeze()` fixed it

You used:

```python
y_train.values.squeeze()
```

Suppose you have:

```text
[[0],
 [1],
 [2],
 [0]]
```

Shape:

```text
(4, 1)
```

`.squeeze()` removes the unnecessary `1` dimension:

```text
[0, 1, 2, 0]
```

Shape:

```text
(4,)
```

So:

```python
y_train_tensor = torch.tensor(
    y_train.values.squeeze(),
    dtype=torch.long
)
```

gives you exactly what `CrossEntropyLoss` needs.

---

# 7. Why `.values`?

`y_train` is a Pandas object.

```python
y_train.values
```

converts it into a NumPy array.

So:

```text
Pandas
  ↓
.values
  ↓
NumPy
  ↓
torch.tensor()
  ↓
PyTorch Tensor
```

---

# 8. Why `long`?

`long` means:

```python
torch.int64
```

For example:

```python
tensor([0, 1, 2, 1], dtype=torch.int64)
```

These are class **indices**.

`CrossEntropyLoss` wants to know:

> "Which class is correct?"

For example:

```text
Sample 1 → class 0
Sample 2 → class 2
Sample 3 → class 1
```

Therefore:

```python
dtype=torch.long
```

---

# 9. ❌ Don't use `reshape(-1, 1)` for this `y`

You previously learned:

```python
y.reshape(-1, 1)
```

That's useful in some **regression** situations.

For example, regression often wants:

```text
[32, 1]
```

But your multiclass classification with:

```python
nn.CrossEntropyLoss()
```

wants:

```text
[32]
```

So remember:

### Regression

```text
y → [32, 1]
```

### Multiclass classification + CrossEntropyLoss

```text
y → [32]
```

---

# 10. Your final correct data pipeline

You should now have:

```python
# Scale X only

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)
```

Then:

```python
# Convert to tensors

x_train_tensor = torch.tensor(
    x_train_scaled,
    dtype=torch.float32
)

x_test_tensor = torch.tensor(
    x_test_scaled,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train.values.squeeze(),
    dtype=torch.long
)

y_test_tensor = torch.tensor(
    y_test.values.squeeze(),
    dtype=torch.long
)
```

Then:

```python
train_dataset = customdataset(
    x_train_tensor,
    y_train_tensor
)

test_dataset = customdataset(
    x_test_tensor,
    y_test_tensor
)
```

Then:

```python
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)
```

---

# 🎯 The most important shapes

For your current model:

```text
X batch
[32, 49]
```

means:

```text
32 samples
49 features
```

Your model:

```text
49 → 32 → 16 → 3
```

produces:

```text
prediction
[32, 3]
```

And your target:

```text
y_batch
[32]
```

contains:

```text
[0, 2, 1, 0, 2, 1, ...]
```

So:

```text
Prediction                 Target

[32, 3]                    [32]
   ↓                          ↓
3 scores per sample       1 class per sample
   ↓                          ↓
        CrossEntropyLoss
               ↓
             Loss
```

### 🧠 Remember this rule

**Multiclass classification:**

```python
model output → [batch_size, number_of_classes]
target       → [batch_size]
target dtype → torch.long
loss         → nn.CrossEntropyLoss()
```

For your project:

```text
[32, 3] → prediction
[32]    → target
long    → target dtype
```

Once you understand this, that particular `multi-target not supported` error will become very easy to recognize.
