In [18]:
import pandas as pd

data = {
    "question": [
        "What is the capital of France?",
        "What is the capital of England?",
        "What is the capital of Italy?",
        "What is the capital of Germany?",
        "What is the capital of Japan?",
        "What is the capital of Pakistan?",
        "What is the largest planet?",
        "What is the smallest planet?",
        "Which planet is known as the Red Planet?",
        "Which planet do we live on?",
        "What is the star closest to Earth?",
        "What is the largest ocean?",
        "What is the largest continent?",
        "What is the fastest land animal?",
        "What is the tallest animal?",
        "What animal is known as the king of the jungle?",
        "What color is grass?",
        "What color is the sky?",
        "What color is snow?",
        "How many days are in a week?",
        "How many months are in a year?",
        "What is two plus two?",
        "What is five plus five?",
        "What is ten minus five?",
        "What is three times three?",
        "Who invented the telephone?",
        "Who discovered penicillin?",
        "Who discovered gravity?",
        "What gas do humans breathe?",
        "What gas do plants absorb?",
        "What organ pumps blood?",
        "What organ helps us think?",
        "What is H2O?",
        "What is HCl?",
        "What is the hardest natural substance?",
        "What is the largest desert?",
        "What is the highest mountain?",
        "What is the smallest ocean?",
        "What is the currency of Japan?",
        "What is the currency of America?"
    ],

    "answer": [
        "Paris",
        "London",
        "Rome",
        "Berlin",
        "Tokyo",
        "Islamabad",
        "Jupiter",
        "Mercury",
        "Mars",
        "Earth",
        "Sun",
        "Pacific",
        "Asia",
        "Cheetah",
        "Giraffe",
        "Lion",
        "Green",
        "Blue",
        "White",
        "Seven",
        "Twelve",
        "Four",
        "Ten",
        "Five",
        "Nine",
        "Bell",
        "Fleming",
        "Newton",
        "Oxygen",
        "Carbon",
        "Heart",
        "Brain",
        "Water",
        "Acid",
        "Diamond",
        "Sahara",
        "Everest",
        "Arctic",
        "Yen",
        "Dollar"
    ]
}

df = pd.DataFrame(data)

In [19]:
df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of England?,London
2,What is the capital of Italy?,Rome
3,What is the capital of Germany?,Berlin
4,What is the capital of Japan?,Tokyo


In [20]:
#tokenise text
def tokenize(text):
    text=text.replace("?","")
    text=text.lower()
    text=text.replace("'","")
    return text.split()#Split into words (tokens)

In [21]:
vocab={"<UNK>":0}

In [22]:
#now apply tokenize and vocab to each question and answer to create 
def build_vocab(row):
    tokenised_question=tokenize(row["question"])
    tokenised_answer=tokenize(row["answer"])

    marged_tokens=tokenised_question + tokenised_answer
    for token in marged_tokens:
        if token not in vocab:
            vocab[token]=len(vocab)

In [23]:
vocab

{'<UNK>': 0}

In [24]:
df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
39    None
dtype: object

In [25]:
len(vocab)

119

In [26]:
print(vocab)

{'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'capital': 4, 'of': 5, 'france': 6, 'paris': 7, 'england': 8, 'london': 9, 'italy': 10, 'rome': 11, 'germany': 12, 'berlin': 13, 'japan': 14, 'tokyo': 15, 'pakistan': 16, 'islamabad': 17, 'largest': 18, 'planet': 19, 'jupiter': 20, 'smallest': 21, 'mercury': 22, 'which': 23, 'known': 24, 'as': 25, 'red': 26, 'mars': 27, 'do': 28, 'we': 29, 'live': 30, 'on': 31, 'earth': 32, 'star': 33, 'closest': 34, 'to': 35, 'sun': 36, 'ocean': 37, 'pacific': 38, 'continent': 39, 'asia': 40, 'fastest': 41, 'land': 42, 'animal': 43, 'cheetah': 44, 'tallest': 45, 'giraffe': 46, 'king': 47, 'jungle': 48, 'lion': 49, 'color': 50, 'grass': 51, 'green': 52, 'sky': 53, 'blue': 54, 'snow': 55, 'white': 56, 'how': 57, 'many': 58, 'days': 59, 'are': 60, 'in': 61, 'a': 62, 'week': 63, 'seven': 64, 'months': 65, 'year': 66, 'twelve': 67, 'two': 68, 'plus': 69, 'four': 70, 'five': 71, 'ten': 72, 'minus': 73, 'three': 74, 'times': 75, 'nine': 76, 'who': 77, 'invented': 78

store indexed text in the indexedtext if input token (user ask) in vocab found in the vocab (my data ) else store it to or return UNK which is 0 The steps are:"hello" is in vocab $\rightarrow$ add 1"aliens" is not in vocab $\rightarrow$ add vocab['<UNK>'], which is 0

Here is the complete walkthrough in formatted Markdown text.

---

# Text to Indices: Step-by-Step Example

### 1. The Setup (Your Vocabulary Data)

Before processing any input, define the known word dictionary (`vocab`). Every word points to a specific numerical ID, and unrecognized words fall back to `<UNK>`.

* `<UNK>` $\rightarrow$ `0` (Unknown word placeholder)
* `hello` $\rightarrow$ `1`
* `world` $\rightarrow$ `2`

---

### 2. User Input

The user inputs the sentence:

> **`"hello aliens"`**

---

### 3. Step-by-Step Breakdown

1. **Tokenize the input**
The sentence is split into individual tokens (words):
`["hello", "aliens"]`
2. **Initialize an empty list**
`indexed_text = []`
3. **Process Token 1: `"hello"**`
* **Check:** Is `"hello"` in `vocab`?
* **Result:** **Yes**. Found in vocabulary.
* **Action:** Retrieve `vocab["hello"]`, which equals `1`.
* **State of list:** `indexed_text = [1]`


4. **Process Token 2: `"aliens"**`
* **Check:** Is `"aliens"` in `vocab`?
* **Result:** **No**. Not in vocabulary.
* **Action:** Fall back to the default token `vocab["<UNK>"]`, which equals `0`.
* **State of list:** `indexed_text = [1, 0]`



---

### 4. Summary Table

| Token | Found in `vocab`? | Value Assigned | Current `indexed_text` |
| --- | --- | --- | --- |
| `"hello"` | **Yes** | `1` | `[1]` |
| `"aliens"` | **No** (Defaults to `<UNK>`) | `0` | `[1, 0]` |

---

### 5. Final Result

The function returns the final list of numerical IDs:

`[1, 0]`

In [29]:
def text_to_indices(text,vocab):
    indexed_text=[]
    for token in tokenize(text):
        if token in vocab:
            indexed_text.append(vocab[token])
        else:
            indexed_text.append(vocab["<UNK>"])
    return indexed_text

In [30]:
text_to_indices("my name is khan",vocab) #only is in ovcab and all others are unknown <UNK>

[0, 0, 2, 0]

In [31]:
text_to_indices("How many days do we have in a week?",vocab)#all are in vocab

[57, 58, 59, 28, 29, 0, 61, 62, 63]

In [32]:
import torch
from torch.utils.data import Dataset,DataLoader

In [33]:
class Qadataset(Dataset):
    def __init__(self,df,vocab):
        self.df=df
        self.vocab=vocab

    def __len__(self):
        return self.df.shape[0]
    
    def __getitem__(self,index):
        numerical_question=text_to_indices(self.df.iloc[index]["question"],self.vocab)
        numerical_answer=text_to_indices(self.df.iloc[index]["answer"],self.vocab)

        return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [34]:
dataset=Qadataset(df,vocab)

In [35]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [36]:
for question,answer in dataloader:
    print(question,answer[0])

tensor([[23, 19, 28, 29, 30, 31]]) tensor([32])
tensor([[ 1,  2, 74, 75, 74]]) tensor([76])
tensor([[ 1,  2,  3, 18, 19]]) tensor([20])
tensor([[ 1, 93, 97, 98, 99]]) tensor([100])
tensor([[ 1,  2,  3, 21, 19]]) tensor([22])
tensor([[77, 81, 84]]) tensor([85])
tensor([[ 1,  2,  3, 41, 42, 43]]) tensor([44])
tensor([[ 1, 93, 94, 95]]) tensor([96])
tensor([[ 1,  2, 71, 69, 71]]) tensor([72])
tensor([[ 1,  2,  3, 45, 43]]) tensor([46])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[  1,   2,   3, 115,   5, 117]]) tensor([118])
tensor([[77, 78,  3, 79]]) tensor([80])
tensor([[ 1, 50,  2, 55]]) tensor([56])
tensor([[ 1,  2, 68, 69, 68]]) tensor([70])
tensor([[57, 58, 59, 60, 61, 62, 63]]) tensor([64])
tensor([[23, 19,  2, 24, 25,  3, 26, 19]]) tensor([27])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([15])
tensor([[57, 58, 65, 60, 61, 62, 66]]) tensor([67])
tensor([[ 1, 86, 28, 87, 88]]) tensor([89])
tensor([[  1,   2, 103]]) tensor([104])
tensor([[ 1,  2,  3,  4,  5, 10]]) tensor([11])
ten

In [43]:
import torch.nn as nn

class simplernn(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding=nn.Embedding(vocab_size,embedding_dim=50)
        self.rnn=nn.RNN(50,64,batch_first=True)
        self.fc=nn.Linear(64,vocab_size)

    def forward(self,question):
        embedded_question=self.embedding(question)
        hidden,final=self.rnn(embedded_question)
        output=self.fc(final.squeeze(0))
        return output

In [44]:
learning_rate=0.001
epochs=25

In [45]:
model=simplernn(len(vocab))

In [46]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [50]:
for epoch in range(epochs):
    total_loss=0
    for question,answer in dataloader:
        optimizer.zero_grad()
        output=model(question)
        loss=criterion(output,answer[:,0])
        loss.backward()
        optimizer.step()
        total_loss=total_loss + loss.item()

    print(f"epochs:{epoch+1},loss :{total_loss:4f}")

epochs:1,loss :0.855552
epochs:2,loss :0.820935
epochs:3,loss :0.788123
epochs:4,loss :0.756981
epochs:5,loss :0.727108
epochs:6,loss :0.700137
epochs:7,loss :0.672730
epochs:8,loss :0.647625
epochs:9,loss :0.624852
epochs:10,loss :0.601021
epochs:11,loss :0.579203
epochs:12,loss :0.559336
epochs:13,loss :0.539574
epochs:14,loss :0.521716
epochs:15,loss :0.502994
epochs:16,loss :0.487138
epochs:17,loss :0.470117
epochs:18,loss :0.454349
epochs:19,loss :0.440351
epochs:20,loss :0.425465
epochs:21,loss :0.412574
epochs:22,loss :0.399067
epochs:23,loss :0.386189
epochs:24,loss :0.374649
epochs:25,loss :0.363558


In [51]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [52]:
predict(model, "capital of japan")

tokyo


In [53]:
import torch

def calculate_accuracy(model, data_loader):
    model.eval()  # Put the model in evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # Turn off gradient calculation to save memory and speed up
        for questions, answers in data_loader:
            # 1. Forward pass: get model predictions
            outputs = model(questions)  # Shape: [batch_size, vocab_size]
            
            # 2. Pick the word ID with the highest score
            # torch.argmax finds the index of the largest value across columns (dim=1)
            predictions = torch.argmax(outputs, dim=1)
            
            # 3. Handle single-token targets:
            # If answers is 2D (like [batch, 1]), flatten to match predictions [batch]
            targets = answers.squeeze()
            
            # 4. Count matches
            correct += (predictions == targets).sum().item()
            total += targets.size(0)

    # 5. Calculate percentage
    accuracy = (correct / total) * 100
    return accuracy

In [57]:
# Assuming you have a test_loader or train_loader:
# Use the existing DataLoader variable: dataloader
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for questions, answers in dataloader:
        predictions = model(questions).argmax(dim=1)
        targets = answers[:, 0]

        correct += (predictions == targets).sum().item()
        total += targets.numel()

acc = 100 * correct / total
print(f"Model Accuracy: {acc:.2f}%")
print(f"Model Accuracy: {acc:.2f}%")

Model Accuracy: 100.00%
Model Accuracy: 100.00%


100 because over dataset is very small